--comment
CREATE SCHEMA IF NOT EXISTS CHEVELLE; USE CHEVELLE; DROP TABLE CHEVELLE.HYPER_PRFL_SILK; 
CREATE EXTERNAL TABLE IF NOT EXISTS CHEVELLE.HYPER_PRFL_SILK(SILKMOTH_RSLT STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY "\034" LINES TERMINATED BY "\012" STORED AS TEXTFILE LOCATION "/${hiveconf:ENVIRONMENT}/EDW/DSODB/OPS/CHEVELLE/HYPER_PROF_RSLT/Output_Silk/";