import { Regexp } from './regexp';
import { RegExp } from './regexp';

export const MOCKREGEXP: Regexp[] = 
[ 
    { "regexp_name": "british nino", "regexp": "^([A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z])([ \\-\\.]?)(\\d{2})\\2?(\\d{2})\\2?(\\d{2})(\\2([ABCD]))?$", "reg_exp_id": "1" }, 
    { "regexp_name": "email address", "regexp": "^(?=[a-zA-Z0-9._-]*@).*(?=[^a-z0-9A-Z._-]*[@]).*(?<![.])@.*", "reg_exp_id": "2" }, 
    { "regexp_name": "french insee", "regexp": "^([1278])(\\d{2})(0\\d|1[0-2])(0[1-9]\\d{3}|1\\d{4}|2[AB1-9]\\d{3}|[3-8]\\d{4}|9[0-5]\\d{3}|97[1-4]\\d{2})(\\d{3})[ \\-]?([0-8]\\d|9[0-7])$", "reg_exp_id": "3" }, 
    { "regexp_name": "italian fiscal code", "regexp": "^([A-Z]{3})([ \\-]?)([A-Z]{3})\\2([0-9L-NP-V]{2})([A-EHLMPRST])([0-9LNP-V]{2})\\2([A-ILMZ][0-9L-NP-V]{3})([A-Z])$", "reg_exp_id": "4" }, 
    { "regexp_name": "name", "regexp": "^[a-zA-Z]{1,15}\s?[a-zA-Z]{1,15}$", "reg_exp_id": "5" }, 
    { "regexp_name": "passport", "regexp": "(?=^[a-zA-Z0-9]{6,10}$)(?=(^[cC])?).*", "reg_exp_id": "6" }, 
    { "regexp_name": "phone number", "regexp": "^([1-9]\d{2})([- .])(\d{3})$2(\d{4})|^[1-9]{1}[0-9]{2}-[0-9]{3}-[0-9]{4}|^[1-9]{1}[0-9]{6,10}|^([\(]{1}[0-9]{3}[\)]{1}[ ]{1}[0-9]{3}[\-]{1}[0-9]{4})$", "reg_exp_id": "7" }, 
    { "regexp_name": "social insurance number", "regexp": "^([0-79]\\d{2})([ \\-\\.]?)(\\d{3})\\2(\\d{3})$", "reg_exp_id": "8" }, 
   // { "regexp_name": "social security number", "regexp": "(?=(^[\d]{3}[-]?))\1(?=([\d]{2}[-]?))\2(?=([\d]{4})$).*", "reg_exp_id": "9" }, 
    { "regexp_name": "spanish nif", "regexp": "(X?)[ \\-]?(\\d{7})[ \\-]?([A-HJ-NP-TV-Z])$", "reg_exp_id": "10" }, 
    { "regexp_name": "street address", "regexp": "(^\d+\s(?:[A-zA-Z0-9]+?)+\s(?:((Avenue|avenue|AVENUE)|(Lane|lane|LANE)|(Road|road|ROAD)|(Boulevard|boulevard|BOULEVARD)|(Drive|drive|DRIVE)|(Street|street|STREET)|(Court|court|COURT)|(Ave|ave|AVE)|(Dr|dr|DR)|(Rd|rd|RD)|(Blvd|blvd|BLVD)|(Ln|ln|LN)|(St|st|ST)|(Str|str/\STR)|(Ct|ct|CT))\.?)|((P\DO\D?|PO)+\.?))", "reg_exp_id": "11" }, 
    { "regexp_name": "tax id", "regexp": "TBD", "reg_exp_id": "12" }, 
    { "regexp_name": "Account Number", "regexp": "^[A-Z0-9<]{6,26}( +)|^[A-Z0-9<]{6,26}$", "reg_exp_id": "13" }, 
    { "regexp_name": "Bank Name", "regexp": "^[a-zA-Z\s]{6,32}$", "reg_exp_id": "14" }, 
    { "regexp_name": "Card Security Code", "regexp": "TBD", "reg_exp_id": "15" }, 
    { "regexp_name": "Credit Report Data", "regexp": "^([0-9]{3})|[a-zA-Z0-9]{1,32}", "reg_exp_id": "16" }, 
    { "regexp_name": "Criminal Background Check", "regexp": "^[1]{1}\-?[0-9A-Za-z]{2,3}\-?[0-9]{1,4}|[a-zA-Z0-9]{3,32}", "reg_exp_id": "17" }, 
    { "regexp_name": "Drivers License Number", "regexp": "^[0-9]{6,14}|[A-Z]{1,3}[0-9]{3,14}|[0-9]{2}[A-Z]{3}[0-9]{5}|[0-9]{3}[A-Z]{2}[0-9]{4}|[0-9]{7}[A-Z]{1}$", "reg_exp_id": "18" }, 
    { "regexp_name": "Email Address", "regexp": "^(?=[a-zA-Z0-9._-]*@).*(?=[^a-z0-9A-Z._-]*[@]).*(?<![.])@.*", "reg_exp_id": "19" }, 
    { "regexp_name": "Expiration Date", "regexp": "(([0-9]{4}[\./-]?)([0][1]|[0][2]|[0][3]|[0][4]|[0][5]|[0][6]|[0][7]|[0][8]|[0][9]|[1][0]|[1][1]|[1][2])[\./-]?([0-9]{2}.*)|(^[0-9]{2}[\./-]?)([0][1]|[0][2]|[0][3]|[0][4]|[0][5]|[0][6]|[0][7]|[0][8]|[0][9]|[1][0]|[1][1]|[1][2])[\./-]?([0-9]{4}.*))", "reg_exp_id": "20" }, 
    { "regexp_name": "Full Magnetic Stripe", "regexp": "[0-1]{1}|[a-zA-Z0-9]{2,32}", "reg_exp_id": "21" }, 
    { "regexp_name": "GCIN", "regexp": "^[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{8,14}|[0-9A-Za-z]{7,34}", "reg_exp_id": "22" }, 
    { "regexp_name": "GMID", "regexp": "(?=^[a-zA-Z0-9]{6}$)(?=^[^0-9]).*", "reg_exp_id": "23" }, 
    { "regexp_name": "GMIN", "regexp": "^(?=[0-9]{9}$).*", "reg_exp_id": "24" }, 
    // { "regexp_name": "Government Identification", "regexp": "^[A-Z0-9<]{9}[0-9]{1}[A-Z]{3}[0-9]{7}[A-Z]{1}[0-9]{7}[A-Z0-9<]{14}[0-9]{2}$^([0-79]\\d{2}| \\-\\.]?|\d{3})\\2(\\d{3})$\d{2}-\d{7}^([A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z]| \\-\\.]?|\d{2})\\2?(\\d{2})\\2?(\\d{2}|\2([ABCD]))?$^([A-Z]{3}|\\-]?|A-Z]{3})\\2([0-9L-NP-V]{2}|A-EHLMPRST]|0-9LNP-V]{2})\\2([A-ILMZ][0-9L-NP-V]{3}|A-Z])$(X?)[ \\-]?(\\d{7})[ \\-]?([A-HJ-NP-TV-Z])$", "reg_exp_id": "25" }, 
    { "regexp_name": "Images Video and Audio", "regexp": "(photo|picture|.jpeg|.png|.gif|.bmp|image)", "reg_exp_id": "26" }, 
    { "regexp_name": "Latitude", "regexp": "^-?(?:90(?:(?:\.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:\.[0-9]{1,6})?))$|^[1-9]{1}[0-9]{1}.[0-9]{5,14}", "reg_exp_id": "27" }, 
    { "regexp_name": "License Plate", "regexp": "(?=(^[a-zA-Z0-9\s?]{5,8})$).*(?=(^[a-zA-Z]{3}|^[0-9]{3}|^[0-9]{1}|^[a-zA-Z]{2}|^[0-9]{2})).*", "reg_exp_id": "28" }, 
    { "regexp_name": "Login ID", "regexp": "^[a-z0-9_-]{3,15}$", "reg_exp_id": "29" }, 
    { "regexp_name": "Longitude", "regexp": "^(?=.)-?((0?[8-9][0-9])|180|([0-1]?[0-7]?[0-9]))?(?:\.[0-9]{1,20})?$", "reg_exp_id": "30" }, 
    { "regexp_name": "Name", "regexp": "^[a-zA-Z]{1,15}\s?[a-zA-Z]{1,15}$", "reg_exp_id": "31" }, 
    { "regexp_name": "Onstar Account Number", "regexp": "^[0-9a-zA-Z]{6,32}|[0-9]{6,32}", "reg_exp_id": "32" }, 
    { "regexp_name": "Password", "regexp": "^(?=.*\d).{4,8}$", "reg_exp_id": "33" }, 
    { "regexp_name": "Phone Number", "regexp": "^([1-9]\d{2})([- .])(\d{3})$2(\d{4})|^[1-9]{1}[0-9]{2}-[0-9]{3}-[0-9]{4}|^[1-9]{1}[0-9]{6,10}|^([\(]{1}[0-9]{3}[\)]{1}[ ]{1}[0-9]{3}[\-]{1}[0-9]{4})$", "reg_exp_id": "34" }, 
    { "regexp_name": "PIN Number", "regexp": "^[0-9]{4}(?!0000)", "reg_exp_id": "35" }, 
    { "regexp_name": "Routing Number", "regexp": "[0-9A-Za-z]{3,60}", "reg_exp_id": "36" }, 
    { "regexp_name": "Service Code", "regexp": "^[A-Za-z0-9]{3,8}$", "reg_exp_id": "37" }, 
    // { "regexp_name": "Social Security Number", "regexp": "(?=(^[\d]{3}[-]?))\1(?=([\d]{2}[-]?))\(?=([\d]{4})$).*", "reg_exp_id": "38" }, 
    { "regexp_name": "Street Address", "regexp": "(^\d+\s(?:[A-zA-Z0-9]+?)+\s(?:((Avenue|avenue|AVENUE)|(Lane|lane|LANE)|(Road|road|ROAD)|(Boulevard|boulevard|BOULEVARD)|(Drive|drive|DRIVE)|(Street|street|STREET)|(Court|court|COURT)|(Ave|ave|AVE)|(Dr|dr|DR)|(Rd|rd|RD)|(Blvd|blvd|BLVD)|(Ln|ln|LN)|(St|st|ST)|(Str|str/\STR)|(Ct|ct|CT))\.?)|((P\DO\D?|PO)+\.?))", "reg_exp_id": "39" }, 
    { "regexp_name": "VIN", "regexp": "^[\d\w^IOQ]{17}$", "reg_exp_id": "40" } 
    ];

    export let ENCREGEXP: Regexp[]  =
    [ 
        { "regexp_name": "british nino", "regexp": "^([A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z])([ ΩΩ-ΩΩ.]?)(ΩΩd{2})ΩΩ2?(ΩΩd{2})ΩΩ2?(ΩΩd{2})(ΩΩ2([ABCD]))?$", "reg_exp_id": "1" }, 
        { "regexp_name": "email address", "regexp": "^(?=[a-zA-Z0-9._-]*@).*(?=[^a-z0-9A-Z._-]*[@]).*(?<![.])@.*", "reg_exp_id": "2" }, 
        { "regexp_name": "french insee", "regexp": "^([1278])(©©d{2})(0ΩΩd|1[0-2])(0[1-9]ΩΩd{3}|1ΩΩd{4}|2[AB1-9]ΩΩd{3}|[3-8]ΩΩd{4}|9[0-5]ΩΩd{3}|97[1-4]ΩΩd{2})(ΩΩd{3})[ ΩΩ-]?([0-8]ΩΩd|9[0-7])$", "reg_exp_id": "3" }, 
        { "regexp_name": "italian fiscal code", "regexp": "^([A-Z]{3})([ ΩΩ-]?)([A-Z]{3})ΩΩ2([0-9L-NP-V]{2})([A-EHLMPRST])([0-9LNP-V]{2})ΩΩ2([A-ILMZ][0-9L-NP-V]{3})([A-Z])$", "reg_exp_id": "4" }, 
        { "regexp_name": "name", "regexp": "^[a-zA-Z]{1,15}Ωs?[a-zA-Z]{1,15}$", "reg_exp_id": "5" }, 
        { "regexp_name": "passport", "regexp": "(?=^[a-zA-Z0-9]{6,10}$)(?=(^[cC])?).*", "reg_exp_id": "6" }, 
        { "regexp_name": "phone number", "regexp": "^([1-9]Ωd{2})([- .])(Ωd{3})$2(Ωd{4})|^[1-9]{1}[0-9]{2}-[0-9]{3}-[0-9]{4}|^[1-9]{1}[0-9]{6,10}|^([Ω(]{1}[0-9]{3}[Ω)]{1}[ ]{1}[0-9]{3}[Ω-]{1}[0-9]{4})$", "reg_exp_id": "7" }, 
        { "regexp_name": "social insurance number", "regexp": "^([0-79]ΩΩd{2})([ ΩΩ-ΩΩ.]?)(ΩΩd{3})ΩΩ2(ΩΩd{3})$", "reg_exp_id": "8" }, 
        { "regexp_name": "social security number", "regexp": "(?=(^[Ωd]{3}[-]?))Ω1(?=([Ωd]{2}[-]?))Ω2(?=([Ωd]{4})$).*", "reg_exp_id": "9" }, 
        { "regexp_name": "spanish nif", "regexp": "(X?)[ ΩΩ-]?(ΩΩd{7})[ ΩΩ-]?([A-HJ-NP-TV-Z])$", "reg_exp_id": "10" }, 
        { "regexp_name": "street address", "regexp": "(^Ωd+Ωs(?:[A-zA-Z0-9]+?)+Ωs(?:((Avenue|avenue|AVENUE)|(Lane|lane|LANE)|(Road|road|ROAD)|(Boulevard|boulevard|BOULEVARD)|(Drive|drive|DRIVE)|(Street|street|STREET)|(Court|court|COURT)|(Ave|ave|AVE)|(Dr|dr|DR)|(Rd|rd|RD)|(Blvd|blvd|BLVD)|(Ln|ln|LN)|(St|st|ST)|(Str|str/ΩSTR)|(Ct|ct|CT))Ω.?)|((PΩDOΩD?|PO)+Ω.?))", "reg_exp_id": "11" }, 
        { "regexp_name": "tax id", "regexp": "TBD", "reg_exp_id": "12" }, 
        { "regexp_name": "Account Number", "regexp": "^[A-Z0-9<]{6,26}( +)|^[A-Z0-9<]{6,26}$", "reg_exp_id": "13" }, 
        { "regexp_name": "Bank Name", "regexp": "^[a-zA-ZΩs]{6,32}$", "reg_exp_id": "14" }, 
        { "regexp_name": "Card Security Code", "regexp": "TBD", "reg_exp_id": "15" }, 
        { "regexp_name": "Credit Report Data", "regexp": "^([0-9]{3})|[a-zA-Z0-9]{1,32}", "reg_exp_id": "16" }, 
        { "regexp_name": "Criminal Background Check", "regexp": "^[1]{1}Ω-?[0-9A-Za-z]{2,3}Ω-?[0-9]{1,4}|[a-zA-Z0-9]{3,32}", "reg_exp_id": "17" }, 
        { "regexp_name": "Drivers License Number", "regexp": "^[0-9]{6,14}|[A-Z]{1,3}[0-9]{3,14}|[0-9]{2}[A-Z]{3}[0-9]{5}|[0-9]{3}[A-Z]{2}[0-9]{4}|[0-9]{7}[A-Z]{1}$", "reg_exp_id": "18" }, 
        { "regexp_name": "Email Address", "regexp": "^(?=[a-zA-Z0-9._-]*@).*(?=[^a-z0-9A-Z._-]*[@]).*(?<![.])@.*", "reg_exp_id": "19" }, 
        { "regexp_name": "Expiration Date", "regexp": "(([0-9]{4}[Ω./-]?)([0][1]|[0][2]|[0][3]|[0][4]|[0][5]|[0][6]|[0][7]|[0][8]|[0][9]|[1][0]|[1][1]|[1][2])[Ω./-]?([0-9]{2}.*)|(^[0-9]{2}[Ω./-]?)([0][1]|[0][2]|[0][3]|[0][4]|[0][5]|[0][6]|[0][7]|[0][8]|[0][9]|[1][0]|[1][1]|[1][2])[Ω./-]?([0-9]{4}.*))", "reg_exp_id": "20" }, 
        { "regexp_name": "Full Magnetic Stripe", "regexp": "[0-1]{1}|[a-zA-Z0-9]{2,32}", "reg_exp_id": "21" }, 
        { "regexp_name": "GCIN", "regexp": "^[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{8,14}|[0-9A-Za-z]{7,34}", "reg_exp_id": "22" }, 
        { "regexp_name": "GMID", "regexp": "(?=^[a-zA-Z0-9]{6}$)(?=^[^0-9]).*", "reg_exp_id": "23" }, 
        { "regexp_name": "GMIN", "regexp": "^(?=[0-9]{9}$).*", "reg_exp_id": "24" }, 
        { "regexp_name": "Government Identification", "regexp": "^[A-Z0-9<]{9}[0-9]{1}[A-Z]{3}[0-9]{7}[A-Z]{1}[0-9]{7}[A-Z0-9<]{14}[0-9]{2}$^([0-79]ΩΩd{2}| ΩΩ-ΩΩ.]?|Ωd{3})ΩΩ2(ΩΩd{3})$Ωd{2}-Ωd{7}^([A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z]| ΩΩ-ΩΩ.]?|Ωd{2})ΩΩ2?(ΩΩd{2})ΩΩ2?(ΩΩd{2}|Ω2([ABCD]))?$^([A-Z]{3}|ΩΩ-]?|A-Z]{3})ΩΩ2([0-9L-NP-V]{2}|A-EHLMPRST]|0-9LNP-V]{2})ΩΩ2([A-ILMZ][0-9L-NP-V]{3}|A-Z])$(X?)[ ΩΩ-]?(ΩΩd{7})[ ΩΩ-]?([A-HJ-NP-TV-Z])$", "reg_exp_id": "25" }, 
        { "regexp_name": "Images Video and Audio", "regexp": "(photo|picture|.jpeg|.png|.gif|.bmp|image)", "reg_exp_id": "26" }, 
        { "regexp_name": "Latitude", "regexp": "^-?(?:90(?:(?:Ω.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:Ω.[0-9]{1,6})?))$|^[1-9]{1}[0-9]{1}.[0-9]{5,14}", "reg_exp_id": "27" }, 
        { "regexp_name": "License Plate", "regexp": "(?=(^[a-zA-Z0-9Ωs?]{5,8})$).*(?=(^[a-zA-Z]{3}|^[0-9]{3}|^[0-9]{1}|^[a-zA-Z]{2}|^[0-9]{2})).*", "reg_exp_id": "28" }, 
        { "regexp_name": "Login ID", "regexp": "^[a-z0-9_-]{3,15}$", "reg_exp_id": "29" }, 
        { "regexp_name": "Longitude", "regexp": "^(?=.)-?((0?[8-9][0-9])|180|([0-1]?[0-7]?[0-9]))?(?:Ω.[0-9]{1,20})?$", "reg_exp_id": "30" }, 
        { "regexp_name": "Name", "regexp": "^[a-zA-Z]{1,15}Ωs?[a-zA-Z]{1,15}$", "reg_exp_id": "31" }, 
        { "regexp_name": "Onstar Account Number", "regexp": "^[0-9a-zA-Z]{6,32}|[0-9]{6,32}", "reg_exp_id": "32" }, 
        { "regexp_name": "Password", "regexp": "^(?=.*Ωd).{4,8}$", "reg_exp_id": "33" }, 
        { "regexp_name": "Phone Number", "regexp": "^([1-9]Ωd{2})([- .])(Ωd{3})$2(Ωd{4})|^[1-9]{1}[0-9]{2}-[0-9]{3}-[0-9]{4}|^[1-9]{1}[0-9]{6,10}|^([Ω(]{1}[0-9]{3}[Ω)]{1}[ ]{1}[0-9]{3}[Ω-]{1}[0-9]{4})$", "reg_exp_id": "34" }, 
        { "regexp_name": "PIN Number", "regexp": "^[0-9]{4}(?!0000)", "reg_exp_id": "35" }, 
        { "regexp_name": "Routing Number", "regexp": "[0-9A-Za-z]{3,60}", "reg_exp_id": "36" }, 
        { "regexp_name": "Service Code", "regexp": "^[A-Za-z0-9]{3,8}$", "reg_exp_id": "37" }, 
        { "regexp_name": "Social Security Number", "regexp": "(?=(^[Ωd]{3}[-]?))Ω1(?=([Ωd]{2}[-]?))Ω(?=([Ωd]{4})$).*", "reg_exp_id": "38" }, 
        { "regexp_name": "Street Address", "regexp": "(^Ωd+Ωs(?:[A-zA-Z0-9]+?)+Ωs(?:((Avenue|avenue|AVENUE)|(Lane|lane|LANE)|(Road|road|ROAD)|(Boulevard|boulevard|BOULEVARD)|(Drive|drive|DRIVE)|(Street|street|STREET)|(Court|court|COURT)|(Ave|ave|AVE)|(Dr|dr|DR)|(Rd|rd|RD)|(Blvd|blvd|BLVD)|(Ln|ln|LN)|(St|st|ST)|(Str|str/ΩSTR)|(Ct|ct|CT))Ω.?)|((PΩDOΩD?|PO)+Ω.?))", "reg_exp_id": "39" }, 
        { "regexp_name": "VIN", "regexp": "^[ΩdΩw^IOQ]{17}$", "reg_exp_id": "40" } 
    ];

    export const REGEXPLISTENC: RegExp[] = 
    [
        { "RegexpId": "1", "RegexpName": "british nino", "Regexp": "^([A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z])([ ©©-©©.]?)(©©d{2})©©2?(©©d{2})©©2?(©©d{2})(©©2([ABCD]))?$" }, 
        { "RegexpId": "2", "RegexpName": "email address", "Regexp": "^(?=[a-zA-Z0-9._-]*@).*(?=[^a-z0-9A-Z._-]*[@]).*(?<![.])@.*" }, 
        { "RegexpId": "3", "RegexpName": "french insee", "Regexp": "^([1278])(©©d{2})(0©©d|1[0-2])(0[1-9]©©d{3}|1©©d{4}|2[AB1-9]©©d{3}|[3-8]©©d{4}|9[0-5]©©d{3}|97[1-4]©©d{2})(©©d{3})[ ©©-]?([0-8]©©d|9[0-7])$" }, 
        { "RegexpId": "4", "RegexpName": "italian fiscal code", "Regexp": "^([A-Z]{3})([ ©©-]?)([A-Z]{3})©©2([0-9L-NP-V]{2})([A-EHLMPRST])([0-9LNP-V]{2})©©2([A-ILMZ][0-9L-NP-V]{3})([A-Z])$" }, 
        { "RegexpId": "5", "RegexpName": "name", "Regexp": "^[a-zA-Z]{1,15}©s?[a-zA-Z]{1,15}$" }, 
        { "RegexpId": "6", "RegexpName": "passport", "Regexp": "(?=^[a-zA-Z0-9]{6,10}$)(?=(^[cC])?).*" }, 
        { "RegexpId": "7", "RegexpName": "phone number", "Regexp": "^([1-9]©d{2})([- .])(©d{3})$2(©d{4})|^[1-9]{1}[0-9]{2}-[0-9]{3}-[0-9]{4}|^[1-9]{1}[0-9]{6,10}|^([©(]{1}[0-9]{3}[©)]{1}[ ]{1}[0-9]{3}[©-]{1}[0-9]{4})$" }, 
        { "RegexpId": "8", "RegexpName": "social insurance number", "Regexp": "^([0-79]©©d{2})([ ©©-©©.]?)(©©d{3})©©2(©©d{3})$" }, 
        { "RegexpId": "9", "RegexpName": "social security number", "Regexp": "(?=(^[©d]{3}[-]?))©1(?=([©d]{2}[-]?))©2(?=([©d]{4})$).*" }, 
        { "RegexpId": "10", "RegexpName": "spanish nif", "Regexp": "(X?)[ ©©-]?(©©d{7})[ ©©-]?([A-HJ-NP-TV-Z])$" }, 
        { "RegexpId": "11", "RegexpName": "street address", "Regexp": "(^©d+©s(?:[A-zA-Z0-9]+?)+©s(?:((Avenue|avenue|AVENUE)|(Lane|lane|LANE)|(Road|road|ROAD)|(Boulevard|boulevard|BOULEVARD)|(Drive|drive|DRIVE)|(Street|street|STREET)|(Court|court|COURT)|(Ave|ave|AVE)|(Dr|dr|DR)|(Rd|rd|RD)|(Blvd|blvd|BLVD)|(Ln|ln|LN)|(St|st|ST)|(Str|str/©STR)|(Ct|ct|CT))©.?)|((P©DO©D?|PO)+©.?))" }, 
        { "RegexpId": "12", "RegexpName": "tax id", "Regexp": "TBD" }, 
        { "RegexpId": "13", "RegexpName": "Account Number", "Regexp": "^[A-Z0-9<]{6,26}( +)|^[A-Z0-9<]{6,26}$" }, 
        { "RegexpId": "14", "RegexpName": "Bank Name", "Regexp": "^[a-zA-Z©s]{6,32}$" }, 
        { "RegexpId": "15", "RegexpName": "Card Security Code", "Regexp": "TBD" }, 
        { "RegexpId": "16", "RegexpName": "Credit Report Data", "Regexp": "^([0-9]{3})|[a-zA-Z0-9]{1,32}" }, 
        { "RegexpId": "17", "RegexpName": "Criminal Background Check", "Regexp": "^[1]{1}©-?[0-9A-Za-z]{2,3}©-?[0-9]{1,4}|[a-zA-Z0-9]{3,32}" }, 
        { "RegexpId": "18", "RegexpName": "Drivers License Number", "Regexp": "^[0-9]{6,14}|[A-Z]{1,3}[0-9]{3,14}|[0-9]{2}[A-Z]{3}[0-9]{5}|[0-9]{3}[A-Z]{2}[0-9]{4}|[0-9]{7}[A-Z]{1}$" }, 
        { "RegexpId": "19", "RegexpName": "Email Address", "Regexp": "^(?=[a-zA-Z0-9._-]*@).*(?=[^a-z0-9A-Z._-]*[@]).*(?<![.])@.*" }, 
        { "RegexpId": "20", "RegexpName": "Expiration Date", "Regexp": "(([0-9]{4}[©./-]?)([0][1]|[0][2]|[0][3]|[0][4]|[0][5]|[0][6]|[0][7]|[0][8]|[0][9]|[1][0]|[1][1]|[1][2])[©./-]?([0-9]{2}.*)|(^[0-9]{2}[©./-]?)([0][1]|[0][2]|[0][3]|[0][4]|[0][5]|[0][6]|[0][7]|[0][8]|[0][9]|[1][0]|[1][1]|[1][2])[©./-]?([0-9]{4}.*))" }, 
        { "RegexpId": "21", "RegexpName": "Full Magnetic Stripe", "Regexp": "[0-1]{1}|[a-zA-Z0-9]{2,32}" }, 
        { "RegexpId": "22", "RegexpName": "GCIN", "Regexp": "^[A-Za-z0-9]{8}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{4}-[A-Za-z0-9]{8,14}|[0-9A-Za-z]{7,34}" }, 
        { "RegexpId": "23", "RegexpName": "GMID", "Regexp": "(?=^[a-zA-Z0-9]{6}$)(?=^[^0-9]).*" }, 
        { "RegexpId": "24", "RegexpName": "GMIN", "Regexp": "^(?=[0-9]{9}$).*" }, 
        { "RegexpId": "25", "RegexpName": "Government Identification", "Regexp": "^[A-Z0-9<]{9}[0-9]{1}[A-Z]{3}[0-9]{7}[A-Z]{1}[0-9]{7}[A-Z0-9<]{14}[0-9]{2}$^([0-79]©©d{2}| ©©-©©.]?|©d{3})©©2(©©d{3})$©d{2}-©d{7}^([A-CEGHJ-PR-TW-Z][A-CEGHJ-NPR-TW-Z]| ©©-©©.]?|©d{2})©©2?(©©d{2})©©2?(©©d{2}|©2([ABCD]))?$^([A-Z]{3}|©©-]?|A-Z]{3})©©2([0-9L-NP-V]{2}|A-EHLMPRST]|0-9LNP-V]{2})©©2([A-ILMZ][0-9L-NP-V]{3}|A-Z])$(X?)[ ©©-]?(©©d{7})[ ©©-]?([A-HJ-NP-TV-Z])$" }, 
        { "RegexpId": "26", "RegexpName": "Images Video and Audio", "Regexp": "(photo|picture|.jpeg|.png|.gif|.bmp|image)" }, 
        { "RegexpId": "27", "RegexpName": "Latitude", "Regexp": "^-?(?:90(?:(?:©.0{1,6})?)|(?:[0-9]|[1-8][0-9])(?:(?:©.[0-9]{1,6})?))$|^[1-9]{1}[0-9]{1}.[0-9]{5,14}" }, 
        { "RegexpId": "28", "RegexpName": "License Plate", "Regexp": "(?=(^[a-zA-Z0-9©s?]{5,8})$).*(?=(^[a-zA-Z]{3}|^[0-9]{3}|^[0-9]{1}|^[a-zA-Z]{2}|^[0-9]{2})).*" }, 
        { "RegexpId": "29", "RegexpName": "Login ID", "Regexp": "^[a-z0-9_-]{3,15}$" }, 
        { "RegexpId": "30", "RegexpName": "Longitude", "Regexp": "^(?=.)-?((0?[8-9][0-9])|180|([0-1]?[0-7]?[0-9]))?(?:©.[0-9]{1,20})?$" }, 
        { "RegexpId": "31", "RegexpName": "Name", "Regexp": "^[a-zA-Z]{1,15}©s?[a-zA-Z]{1,15}$" }, 
        { "RegexpId": "32", "RegexpName": "Onstar Account Number", "Regexp": "^[0-9a-zA-Z]{6,32}|[0-9]{6,32}" }, 
        { "RegexpId": "33", "RegexpName": "Password", "Regexp": "^(?=.*©d).{4,8}$" }, 
        { "RegexpId": "34", "RegexpName": "Phone Number", "Regexp": "^([1-9]©d{2})([- .])(©d{3})$2(©d{4})|^[1-9]{1}[0-9]{2}-[0-9]{3}-[0-9]{4}|^[1-9]{1}[0-9]{6,10}|^([©(]{1}[0-9]{3}[©)]{1}[ ]{1}[0-9]{3}[©-]{1}[0-9]{4})$" }, 
        { "RegexpId": "35", "RegexpName": "PIN Number", "Regexp": "^[0-9]{4}(?!0000)" }, 
        { "RegexpId": "36", "RegexpName": "Routing Number", "Regexp": "[0-9A-Za-z]{3,60}" }, 
        { "RegexpId": "37", "RegexpName": "Service Code", "Regexp": "^[A-Za-z0-9]{3,8}$" }, 
        { "RegexpId": "38", "RegexpName": "Social Security Number", "Regexp": "(?=(^[©d]{3}[-]?))©1(?=([©d]{2}[-]?))©2(?=([©d]{4})$).*" }, 
        { "RegexpId": "39", "RegexpName": "Street Address", "Regexp": "(^©d+©s(?:[A-zA-Z0-9]+?)+©s(?:((Avenue|avenue|AVENUE)|(Lane|lane|LANE)|(Road|road|ROAD)|(Boulevard|boulevard|BOULEVARD)|(Drive|drive|DRIVE)|(Street|street|STREET)|(Court|court|COURT)|(Ave|ave|AVE)|(Dr|dr|DR)|(Rd|rd|RD)|(Blvd|blvd|BLVD)|(Ln|ln|LN)|(St|st|ST)|(Str|str/©STR)|(Ct|ct|CT))©.?)|((P©DO©D?|PO)+©.?))" }, 
        { "RegexpId": "40", "RegexpName": "VIN", "Regexp": "^[©d©w^IOQ]{17}$" }, 
        { "RegexpId": "41", "RegexpName": "BasicStat", "Regexp": "" } 
    ];

    